import { StyleSheet } from 'react-native';
import { Theme } from '../../theme';

export const createSelectedDafCardStyles = (theme: Theme) =>
  StyleSheet.create({
    container: { paddingTop: 0 },
    navHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
      direction: 'rtl',
    },
    dayNavBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 12,
      backgroundColor: theme.colors.accentLight,
      borderWidth: 1,
      borderColor: theme.colors.accent + '33',
    },
    dayNavBtnText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.accent,
    },
    dateCenter: {
      alignItems: 'center',
      flex: 1,
      paddingHorizontal: 8,
    },
    hebDate: {
      fontSize: 15,
      fontWeight: '900',
      color: theme.colors.primary,
      textAlign: 'center',
    },
    gregDate: {
      fontSize: 10,
      fontWeight: '600',
      color: theme.colors.textMuted,
      marginTop: 2,
      textAlign: 'center',
    },
    eventBadge: {
      marginTop: 4,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 6,
      backgroundColor: theme.colors.accentLight,
      borderWidth: 1,
      borderColor: theme.colors.accentBorder,
    },
    eventBadgeText: {
      fontSize: 11,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    dafInfoCard: {
      backgroundColor: theme.colors.background,
      borderRadius: 20,
      paddingVertical: 16,
      paddingHorizontal: 16,
      alignItems: 'center',
      marginBottom: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    masechetName: {
      fontSize: 28,
      fontWeight: '900',
      color: theme.colors.primary,
      letterSpacing: -0.4,
      marginBottom: 4,
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    dafRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    dafDivider: { width: 20, height: 1.2, backgroundColor: 'rgba(201,150,60,0.3)', borderRadius: 1 },
    dafText: { fontSize: 18, fontWeight: '800', color: theme.colors.accent },
    sharedNote: {
      marginTop: 8,
      fontSize: 14,
      fontWeight: '700',
      color: theme.colors.textSecondary,
      textAlign: 'center',
      writingDirection: 'rtl',
      alignSelf: 'stretch',
      width: '100%',
    },
    actions: { gap: 10 },
    partialStatusText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.accent,
      textAlign: 'center',
      writingDirection: 'rtl',
      width: '100%',
      marginBottom: 6,
    },
    toggleBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      height: 54,
      borderRadius: 16,
      borderWidth: 1.5,
      gap: 8,
    },
    toggleBtnPending: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },
    toggleBtnPartial: {
      backgroundColor: theme.colors.accentLight,
      borderColor: theme.colors.accent + '80',
    },
    toggleBtnLearned: {
      backgroundColor: theme.colors.success,
      borderColor: theme.colors.success,
    },
    toggleIconWrapper: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    toggleText: { fontSize: 15, fontWeight: '900', letterSpacing: -0.1 },
    toggleTextFilled: { color: theme.colors.white },
    toggleTextPartial: { color: theme.colors.accent },
    catchUpCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      paddingHorizontal: 12,
      backgroundColor: theme.colors.accentLight,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: theme.colors.accentBorder,
      direction: 'rtl',
    },
    catchUpRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    catchUpIconWrapper: {
      width: 32,
      height: 32,
      borderRadius: 10,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.accentBorder,
    },
    catchUpTextCol: {
      alignItems: 'flex-start',
    },
    catchUpTitle: {
      fontSize: 13,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    catchUpSubtitle: {
      fontSize: 11,
      fontWeight: '600',
      color: theme.colors.textSecondary,
      marginTop: 1,
    },
    catchUpActionBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 10,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.accentBorder,
    },
    catchUpActionText: {
      fontSize: 11,
      fontWeight: '800',
      color: theme.colors.accent,
    },
    tzuratIconWrapper: {
      width: 26,
      height: 26,
      borderRadius: 13,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tzuratBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      height: 52,
      backgroundColor: theme.colors.background,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: theme.colors.accent,
      gap: 8,
      marginBottom: 8,
    },
    tzuratText: { color: theme.colors.textPrimary, fontWeight: '800', fontSize: 15 },
  });
