import { Platform, StyleSheet } from 'react-native';
import type { Theme } from '../../../theme';

export function createContentLicensesModalStyles(theme: Theme) {
  const textAlignment = Platform.OS === 'web' ? 'right' : 'left';

  return StyleSheet.create({
    content: {
      direction: 'rtl',
      maxHeight: '100%',
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 14,
      direction: 'rtl',
    },
    headerTitleGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      flex: 1,
      direction: 'rtl',
    },
    headerIconCircle: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.colors.accentLight,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.accentBorder,
    },
    title: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
      textAlign: textAlignment,
      writingDirection: 'rtl',
    },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.colors.background,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    scrollArea: {
      maxHeight: 420,
    },
    scrollContent: {
      paddingBottom: 8,
      gap: 12,
    },
    intro: {
      fontSize: 13.5,
      lineHeight: 20,
      color: theme.colors.textSecondary,
      textAlign: textAlignment,
      writingDirection: 'rtl',
      alignSelf: 'stretch',
      width: '100%',
    },
    entryCard: {
      backgroundColor: theme.colors.background,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 14,
      gap: 8,
      direction: 'rtl',
    },
    entryHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      direction: 'rtl',
    },
    entryTitle: {
      flex: 1,
      fontSize: 15,
      fontWeight: '800',
      color: theme.colors.textPrimary,
      textAlign: textAlignment,
      writingDirection: 'rtl',
    },
    licenseBadge: {
      flexShrink: 0,
      backgroundColor: theme.colors.accentLight,
      borderWidth: 1,
      borderColor: theme.colors.accentBorder,
      paddingHorizontal: 10,
      paddingVertical: 3,
      borderRadius: theme.radius.full,
    },
    licenseBadgeText: {
      fontSize: 11.5,
      fontWeight: '700',
      color: theme.colors.accent,
    },
    entryText: {
      fontSize: 13.5,
      lineHeight: 20,
      color: theme.colors.textSecondary,
      textAlign: textAlignment,
      writingDirection: 'rtl',
      alignSelf: 'stretch',
      width: '100%',
    },
    linkRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      direction: 'rtl',
    },
    linkChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: theme.radius.full,
    },
    linkChipText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.colors.accent,
      writingDirection: 'rtl',
    },
    noteRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
      paddingHorizontal: 2,
      direction: 'rtl',
    },
    noteText: {
      flex: 1,
      fontSize: 12.5,
      lineHeight: 18,
      color: theme.colors.textMuted,
      textAlign: textAlignment,
      writingDirection: 'rtl',
    },
    badgeRow: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    closeAction: {
      marginTop: 16,
      paddingVertical: 14,
      borderRadius: theme.radius.md,
      backgroundColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    closeActionText: {
      fontSize: 15,
      fontWeight: '700',
      color: theme.colors.white,
    },
  });
}
