import { StyleSheet, Platform } from 'react-native';
import { Theme } from '../../../theme';

export function createResetConfirmModalStyles(theme: Theme) {
  const textAlignment = Platform.OS === 'web' ? 'right' : 'left';
  return StyleSheet.create({
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
      direction: 'rtl',
    },
    headerTitleGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      direction: 'rtl',
    },
    headerIconCircle: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: 'rgba(239, 68, 68, 0.12)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    title: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
      textAlign: textAlignment,
      writingDirection: 'rtl',
    },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.colors.background,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    contentBox: {
      backgroundColor: theme.colors.background,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 16,
      marginBottom: 16,
      direction: 'rtl',
    },
    message: {
      fontSize: 15,
      color: theme.colors.textSecondary,
      lineHeight: 22,
      textAlign: textAlignment,
      writingDirection: 'rtl',
      alignSelf: 'stretch',
      width: '100%',
    },
    warningRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: 'rgba(239, 68, 68, 0.08)',
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: theme.radius.md,
      marginBottom: 20,
      borderWidth: 1,
      borderColor: 'rgba(239, 68, 68, 0.2)',
      direction: 'rtl',
    },
    warningText: {
      flex: 1,
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.danger,
      lineHeight: 18,
      textAlign: textAlignment,
      writingDirection: 'rtl',
    },
    buttonRow: {
      flexDirection: 'row',
      gap: 12,
      width: '100%',
      direction: 'rtl',
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: theme.radius.md,
      backgroundColor: theme.colors.background,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cancelButtonText: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.colors.textSecondary,
    },
    confirmButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: theme.radius.md,
      backgroundColor: theme.colors.danger,
      alignItems: 'center',
      justifyContent: 'center',
    },
    confirmButtonText: {
      fontSize: 15,
      fontWeight: '700',
      color: '#ffffff',
    },
  });
}
