import { Platform, StyleSheet } from 'react-native';
import type { Theme } from '../../../theme';

export function createSiyumNusachModalStyles(theme: Theme) {
  const textAlignment = Platform.OS === 'web' ? 'right' : 'left';

  return StyleSheet.create({
    content: {
      direction: 'rtl',
      maxHeight: '100%',
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
      direction: 'rtl',
    },
    headerTitleGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      flex: 1,
      direction: 'rtl',
    },
    headerIconCircle: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.colors.accentLight,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.accentBorder,
    },
    title: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
      textAlign: textAlignment,
      writingDirection: 'rtl',
    },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.colors.background,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    pickerToggle: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.background,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: theme.radius.md,
      paddingHorizontal: 14,
      paddingVertical: 10,
      marginBottom: 8,
      direction: 'rtl',
    },
    pickerToggleOpen: {
      borderColor: theme.colors.accentBorder,
      backgroundColor: theme.colors.accentLight,
    },
    pickerToggleText: {
      flex: 1,
      fontSize: 15,
      fontWeight: '700',
      color: theme.colors.textPrimary,
      textAlign: textAlignment,
      writingDirection: 'rtl',
    },
    pickerList: {
      height: 220,
      marginBottom: 12,
    },
    scrollArea: {
      maxHeight: 480,
    },
    scrollContent: {
      paddingBottom: 8,
      gap: 14,
    },
    sectionCard: {
      backgroundColor: theme.colors.background,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 14,
      gap: 8,
      direction: 'rtl',
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: theme.colors.accent,
      textAlign: textAlignment,
      writingDirection: 'rtl',
      alignSelf: 'stretch',
      width: '100%',
    },
    sectionBody: {
      fontSize: 16,
      lineHeight: 28,
      color: theme.colors.textPrimary,
      textAlign: textAlignment,
      writingDirection: 'rtl',
      alignSelf: 'stretch',
      width: '100%',
    },
    sectionNote: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.textMuted,
      textAlign: textAlignment,
      writingDirection: 'rtl',
      alignSelf: 'stretch',
      width: '100%',
    },
    attributionCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 12,
      gap: 8,
      direction: 'rtl',
    },
    attributionText: {
      fontSize: 12.5,
      lineHeight: 18,
      color: theme.colors.textMuted,
      textAlign: textAlignment,
      writingDirection: 'rtl',
      alignSelf: 'stretch',
      width: '100%',
    },
    linkRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      direction: 'rtl',
    },
    linkChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      backgroundColor: theme.colors.background,
      borderWidth: 1,
      borderColor: theme.colors.border,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: theme.radius.full,
    },
    linkChipText: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.colors.accent,
      writingDirection: 'rtl',
    },
  });
}
