import { Platform, StyleSheet } from 'react-native';
import { useTheme } from '../../theme';

export const createHomeHeroCardStyles = (theme: ReturnType<typeof useTheme>) =>
  StyleSheet.create({
    dafCard: {
      backgroundColor: theme.colors.surface,
      marginHorizontal: 20,
      borderRadius: 32,
      borderWidth: 2,
      borderColor: theme.colors.border,
      ...theme.shadow.hero,
    },
    dafCardInner: {
      overflow: 'hidden',
      borderRadius: 32,
      padding: 24,
    },
    cardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    dailyStudyBadge: {
      backgroundColor: theme.colors.accentLight,
      paddingHorizontal: 12,
      paddingVertical: 5,
      borderRadius: 10,
    },
    dailyStudyText: {
      color: theme.colors.accent,
      fontSize: 12,
      fontWeight: '800',
      letterSpacing: 0.3,
    },
    masechetPressable: {
      marginBottom: 18,
    },
    masechetRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    masechetContent: {
      flex: 1,
    },
    masechetName: {
      fontSize: 38,
      fontWeight: '900',
      color: theme.colors.textPrimary,
      textAlign: Platform.OS === 'web' ? 'right' : 'left',
      writingDirection: 'rtl',
      letterSpacing: -0.5,
      lineHeight: 46,
    },
    masechetSubRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 6,
    },
    dafBadge: {
      backgroundColor: theme.colors.accentLight,
      paddingHorizontal: 10,
      paddingVertical: 3,
      borderRadius: 8,
    },
    dafBadgeTextMain: {
      fontSize: 15,
      fontWeight: '800',
      color: theme.colors.accent,
    },
    sharedNote: {
      marginTop: 6,
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textSecondary,
      textAlign: Platform.OS === 'web' ? 'right' : 'left',
      writingDirection: 'rtl',
      width: '100%',
    },
    masechetChevronRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingStart: 8,
      backgroundColor: theme.colors.background,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: theme.radius.full,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    masechetBrowseAll: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.accent,
    },
    progressSection: {
      marginBottom: 20,
      gap: 8,
    },
    progressHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    progressTitle: {
      color: theme.colors.textSecondary,
      fontSize: 12,
      fontWeight: '700',
    },
    progressValue: {
      color: theme.colors.accent,
      fontSize: 13,
      fontWeight: '800',
    },
    progressBarBg: {
      height: 6,
      backgroundColor: theme.colors.progressTrack,
      borderRadius: 4,
      overflow: 'hidden',
    },
    progressBarFill: {
      height: '100%',
      backgroundColor: theme.colors.accent,
      borderRadius: 4,
    },
    actionsContainer: {
      gap: 12,
    },
    studyPrimaryBtn: {
      height: 56,
      borderRadius: 20,
      backgroundColor: theme.colors.accent,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      shadowColor: theme.colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 5,
    },
    studyPrimaryText: {
      color: theme.colors.white,
      fontSize: 16,
      fontWeight: '800',
    },
    markSecondaryBtn: {
      height: 50,
      borderRadius: 18,
      borderWidth: 1.5,
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.background,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    markSecondaryText: {
      color: theme.colors.accent,
      fontSize: 15,
      fontWeight: '800',
    },
    markPartialBtn: {
      height: 50,
      borderRadius: 18,
      borderWidth: 1.5,
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.accentLight,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    markPartialText: {
      color: theme.colors.accent,
      fontSize: 15,
      fontWeight: '800',
    },
    learnedSuccessBtn: {
      height: 48,
      borderRadius: 16,
      backgroundColor: theme.colors.successLight,
      borderWidth: 1,
      borderColor: theme.colors.success + '40',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    learnedSuccessText: {
      color: theme.colors.success,
      fontSize: 14,
      fontWeight: '800',
    },
    partialStatusText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.accent,
      textAlign: Platform.OS === 'web' ? 'right' : 'left',
      writingDirection: 'rtl',
      alignSelf: 'stretch',
    },
    halfDafTip: {
      backgroundColor: theme.colors.background,
      borderRadius: 14,
      paddingVertical: 9,
      paddingHorizontal: 12,
      borderWidth: 1,
      borderColor: theme.colors.accentBorder,
    },
    halfDafTipInner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    halfDafTipText: {
      flex: 1,
      fontSize: 12,
      lineHeight: 17,
      color: theme.colors.textSecondary,
      fontWeight: '600',
      textAlign: Platform.OS === 'web' ? 'right' : 'left',
      writingDirection: 'rtl',
    },
    halfDafTipBold: {
      color: theme.colors.textPrimary,
      fontWeight: '800',
    },
    halfDafTipDismiss: {
      padding: 4,
    },
    halfDafLink: {
      alignSelf: 'center',
      paddingVertical: 4,
    },
    halfDafLinkText: {
      color: theme.colors.accent,
      fontSize: 13,
      fontWeight: '700',
    },
    swipeHintRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      marginTop: 14,
      opacity: 0.6,
    },
    swipeHintDot: {
      width: 4,
      height: 4,
      borderRadius: 2,
      backgroundColor: theme.colors.textSecondary,
    },
    swipeHintActiveDot: {
      width: 14,
      height: 4,
      borderRadius: 2,
      backgroundColor: theme.colors.accent,
    },
  });

export type HomeHeroCardStyles = ReturnType<typeof createHomeHeroCardStyles>;
