import { StyleSheet } from 'react-native';
import type { Theme } from '../../theme';
import { CARD_SIZE } from '../../utils/shareProgressImage';

export function createSiyumShareCardStyles(theme: Theme) {
  return StyleSheet.create({
    root: {
      width: CARD_SIZE,
      height: CARD_SIZE,
      direction: 'rtl',
      overflow: 'hidden',
      backgroundColor: theme.colors.surface,
    },
    decorTop: {
      position: 'absolute',
      top: -120,
      right: -80,
      width: 440,
      height: 440,
      borderRadius: 220,
      backgroundColor: theme.colors.accentLight,
    },
    decorBottom: {
      position: 'absolute',
      bottom: -100,
      left: -100,
      width: 380,
      height: 380,
      borderRadius: 190,
      backgroundColor: theme.colors.accentLight,
    },
    content: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 64,
    },
    ribbonOuter: {
      marginBottom: 36,
      ...theme.shadow.gold,
      borderRadius: 140,
    },
    ribbonRing: {
      width: 240,
      height: 240,
      borderRadius: 120,
      padding: 8,
      borderWidth: 2,
      borderColor: theme.colors.accentBorder,
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
      backgroundColor: theme.colors.surface,
    },
    ribbonInner: {
      width: 210,
      height: 210,
      borderRadius: 105,
      backgroundColor: theme.colors.accentLight,
      justifyContent: 'center',
      alignItems: 'center',
    },
    title: {
      fontSize: 72,
      fontWeight: '900',
      color: theme.colors.accent,
      textAlign: 'center',
      marginBottom: 16,
    },
    subtitle: {
      fontSize: 44,
      fontWeight: '800',
      color: theme.colors.textPrimary,
      textAlign: 'center',
      writingDirection: 'rtl',
      width: '100%',
      marginBottom: 36,
    },
    pagesPill: {
      paddingVertical: 24,
      paddingHorizontal: 48,
      borderRadius: theme.radius.full,
      backgroundColor: theme.colors.surface,
      borderWidth: 1.5,
      borderColor: theme.colors.accentBorder,
      ...theme.shadow.cardMedium,
    },
    pagesText: {
      fontSize: 36,
      fontWeight: '800',
      color: theme.colors.textSecondary,
      textAlign: 'center',
      writingDirection: 'rtl',
    },
    footer: {
      paddingBottom: 48,
      paddingTop: 8,
    },
    footerLineWrap: {
      alignItems: 'center',
      marginBottom: 28,
      paddingHorizontal: 100,
    },
    footerLine: {
      height: 4,
      width: '100%',
      maxWidth: 520,
      borderRadius: 2,
      backgroundColor: theme.colors.accent,
      opacity: 0.85,
    },
    branding: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 24,
      paddingHorizontal: 32,
    },
    logoOuter: {
      padding: 12,
      borderRadius: 22,
      backgroundColor: theme.colors.surface,
      borderWidth: 1,
      borderColor: theme.colors.accentBorder,
      ...theme.shadow.card,
    },
    logo: {
      width: 56,
      height: 56,
      borderRadius: 14,
    },
    appName: {
      fontSize: 36,
      fontWeight: '900',
      color: theme.colors.textPrimary,
    },
    appTagline: {
      fontSize: 23,
      fontWeight: '600',
      color: theme.colors.textMuted,
      marginTop: 4,
    },
  });
}
