import { StyleSheet } from 'react-native';
import { useTheme } from '../../theme';

export const guideBadgeStyles = StyleSheet.create({
  badgeInline: {
    fontSize: 12,
    fontWeight: '800',
    borderRadius: 6,
    borderWidth: 1,
    overflow: 'hidden',
  },
});

export const createGuideModalStyles = (theme: ReturnType<typeof useTheme>) =>
  StyleSheet.create({
    overlayRoot: {
      flex: 1,
    },
    overlayDim: {
      backgroundColor: 'rgba(0, 0, 0, 0.65)',
    },
    sheetLayer: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
    },
    sheetFill: {
      flex: 1,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      overflow: 'hidden',
      backgroundColor: theme.colors.background,
    },
    modalSafe: {
      flex: 1,
      backgroundColor: theme.colors.background,
      direction: 'rtl',
    },
    handleSpacing: {
      paddingTop: 8,
      paddingBottom: 4,
      backgroundColor: theme.colors.surface,
    },
    modalHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 14,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.border,
      backgroundColor: theme.colors.surface,
    },
    modalTitle: {
      fontSize: 19,
      fontWeight: '900',
      color: theme.colors.primary,
    },
    modalSubtitle: {
      fontSize: 12,
      color: theme.colors.textMuted,
      marginTop: 2,
    },
    closeBtn: {
      paddingHorizontal: 14,
      paddingVertical: 7,
      backgroundColor: theme.colors.background,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    closeBtnText: {
      color: theme.colors.accent,
      fontWeight: '700',
      fontSize: 13,
    },
    modalScroll: {
      flex: 1,
    },
    modalContent: {
      padding: 16,
    },
    searchBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.colors.border,
      gap: 10,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: theme.colors.textPrimary,
      textAlign: 'start' as any,
      padding: 0,
    },
    chipsScrollView: {
      marginBottom: 14,
      direction: 'ltr',
    },
    chipsContainer: {
      flexDirection: 'row-reverse',
      gap: 8,
      paddingHorizontal: 4,
    },
    faqChip: {
      flexDirection: 'row',
      direction: 'rtl',
      alignItems: 'center',
      gap: 6,
      flexShrink: 0,
      backgroundColor: theme.colors.surface,
      borderRadius: 20,
      paddingHorizontal: 14,
      paddingVertical: 7,
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    faqChipSelected: {
      backgroundColor: theme.colors.accentLight,
      borderColor: theme.colors.accent,
    },
    faqChipText: {
      fontSize: 13,
      fontWeight: '600',
      color: theme.colors.textSecondary,
      writingDirection: 'rtl',
    },
    faqChipTextSelected: {
      color: theme.colors.accent,
      fontWeight: '800',
    },
    controlsRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 16,
      marginBottom: 14,
      paddingHorizontal: 4,
    },
    controlBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    controlBtnText: {
      fontSize: 12,
      fontWeight: '700',
      color: theme.colors.accent,
    },
    controlBtnTextMuted: {
      fontSize: 12,
      fontWeight: '600',
      color: theme.colors.textMuted,
    },
    searchResultsInfo: {
      marginBottom: 12,
      paddingHorizontal: 4,
    },
    searchResultsText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.accent,
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: 36,
      paddingHorizontal: 20,
      gap: 10,
    },
    emptyTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    emptySubtitle: {
      fontSize: 13,
      color: theme.colors.textMuted,
      textAlign: 'center',
      lineHeight: 20,
    },
    clearSearchBtn: {
      marginTop: 8,
      paddingHorizontal: 16,
      paddingVertical: 8,
      backgroundColor: theme.colors.accentLight,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.colors.accent,
    },
    clearSearchBtnText: {
      fontSize: 13,
      fontWeight: '700',
      color: theme.colors.accent,
    },
    sectionCard: {
      backgroundColor: theme.colors.surface,
      borderRadius: 16,
      marginBottom: 14,
      borderWidth: 1,
      borderColor: theme.colors.border,
      overflow: 'hidden',
    },
    sectionHeaderTouchable: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: 14,
      gap: 12,
    },
    iconBox: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: theme.colors.accentLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sectionTitleContainer: {
      flex: 1,
    },
    sectionTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: theme.colors.primary,
    },
    sectionCountText: {
      fontSize: 11,
      color: theme.colors.textMuted,
      marginTop: 2,
    },
    itemsList: {
      gap: 12,
      paddingHorizontal: 14,
      paddingBottom: 16,
      paddingTop: 4,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
    },
    item: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      paddingRight: 4,
    },
    bullet: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: theme.colors.accent,
      marginTop: 7,
    },
    itemText: {
      flex: 1,
      fontSize: 14,
      lineHeight: 22,
      color: theme.colors.textSecondary,
      fontWeight: '500',
    },
    itemTextBold: {
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    contactBox: {
      backgroundColor: theme.colors.accentLight,
      borderRadius: 16,
      padding: 16,
      marginTop: 8,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: theme.colors.accentBorder,
    },
    contactHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginBottom: 10,
    },
    contactTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: theme.colors.primary,
    },
    contactIntro: {
      fontSize: 13,
      lineHeight: 20,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      fontWeight: '500',
      marginBottom: 10,
    },
    contactEmail: {
      fontSize: 15,
      fontWeight: '800',
      color: theme.colors.accent,
      textAlign: 'center',
    },
    footerCard: {
      width: '100%',
      alignItems: 'center',
      backgroundColor: theme.colors.surface,
      borderRadius: 22,
      paddingVertical: 22,
      paddingHorizontal: 18,
      borderWidth: 1,
      borderColor: theme.colors.border,
      ...theme.shadow.card,
      position: 'relative',
      overflow: 'hidden',
      marginTop: 18,
      marginBottom: 8,
    },
    footerGradient: {
      ...StyleSheet.absoluteFill,
      borderRadius: 22,
    },
    footerIconHalo: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: theme.colors.accentLight,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
      borderWidth: 1.5,
      borderColor: theme.colors.accentBorder,
    },
    footerCardTitle: {
      fontSize: 16,
      fontWeight: '800',
      color: theme.colors.primary,
      letterSpacing: -0.2,
      textAlign: 'center',
      marginBottom: 10,
    },
    footerTextContainer: {
      width: '100%',
      paddingHorizontal: 4,
    },
    footerText: {
      fontSize: 13,
      lineHeight: 22,
      color: theme.colors.textSecondary,
      textAlign: 'center',
      fontWeight: '500',
    },
    footerTextBold: {
      fontWeight: '800',
      color: theme.colors.textPrimary,
    },
    footerDividerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '60%',
      marginVertical: 14,
      gap: 10,
    },
    footerDividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: theme.colors.border,
    },
    footerWishBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: theme.colors.accentLight,
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.colors.accentBorder,
    },
    footerWishText: {
      color: theme.colors.textPrimary,
      fontSize: 12,
      fontWeight: '700',
    },
  });

export type GuideModalStyles = ReturnType<typeof createGuideModalStyles>;
