export const THEME = {
  colors: {
    background: '#F5F2EA',
    surface: '#FFFFFF',
    primary: '#1E293B',
    accent: '#C9963C',
    accentLight: '#FDF3DC',
    accentBorder: 'rgba(201,150,60,0.25)',
    success: '#22C55E',
    successLight: '#DCFCE7',
    danger: '#EF4444',
    dangerLight: '#FEE2E2',
    muted: '#94A3B8',
    textPrimary: '#1E293B',
    textSecondary: '#64748B',
    textMuted: '#94A3B8',
    border: '#E8E3D8',
    tabBar: '#1E293B',
  },
  radius: {
    sm: 12,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 40,
    full: 9999,
  },
  shadow: {
    card: {
      shadowColor: '#1E293B',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 3,
    },
    cardMedium: {
      shadowColor: '#1E293B',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 16,
      elevation: 5,
    },
    hero: {
      shadowColor: '#1E293B',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.14,
      shadowRadius: 24,
      elevation: 10,
    },
    gold: {
      shadowColor: '#C9963C',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 6,
    },
    tabBar: {
      shadowColor: '#C9963C',
      shadowOffset: { width: 0, height: -2 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 8,
    },
  },
} as const;
