import { StyleSheet, Platform } from 'react-native';
import { Theme } from '../../theme';

export function createClearCacheModalStyles(theme: Theme) {
  const textAlignment = Platform.OS === 'web' ? 'right' : 'left';
  return StyleSheet.create({
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.65)',
      justifyContent: 'flex-end',
    },
    container: {
      backgroundColor: theme.colors.surface,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 24,
      borderTopWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderColor: theme.colors.border,
      maxHeight: '90%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 20,
      direction: 'rtl',
    },
    dragHandle: {
      width: 42,
      height: 4.5,
      borderRadius: 2.5,
      backgroundColor: theme.colors.border,
      alignSelf: 'center',
      marginBottom: 16,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
      direction: 'rtl',
    },
    headerTitleGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      direction: 'rtl',
    },
    headerIconCircle: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.colors.accentLight,
      alignItems: 'center',
      justifyContent: 'center',
    },
    title: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
      textAlign: textAlignment,
      writingDirection: 'rtl',
    },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.colors.background,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    contentBox: {
      backgroundColor: theme.colors.background,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 16,
      marginBottom: 16,
      direction: 'rtl',
    },
    message: {
      fontSize: 15,
      color: theme.colors.textSecondary,
      lineHeight: 22,
      textAlign: textAlignment,
      writingDirection: 'rtl',
      alignSelf: 'stretch',
      width: '100%',
      marginBottom: 12,
    },
    sizeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: theme.colors.surface,
      borderRadius: theme.radius.md,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderWidth: 1,
      borderColor: theme.colors.accentBorder,
      direction: 'rtl',
    },
    sizeLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: theme.colors.textPrimary,
      textAlign: textAlignment,
      writingDirection: 'rtl',
    },
    sizeValueBadge: {
      backgroundColor: theme.colors.accentLight,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: theme.radius.full,
    },
    sizeValueText: {
      fontSize: 14,
      fontWeight: '700',
      color: theme.colors.accent,
    },
    safeNoteRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 20,
      paddingHorizontal: 4,
      direction: 'rtl',
    },
    safeNoteText: {
      flex: 1,
      fontSize: 13,
      color: theme.colors.textMuted,
      lineHeight: 18,
      textAlign: textAlignment,
      writingDirection: 'rtl',
    },
    buttonRow: {
      flexDirection: 'row',
      gap: 12,
      width: '100%',
      direction: 'rtl',
    },
    cancelButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: theme.radius.md,
      backgroundColor: theme.colors.background,
      borderWidth: 1,
      borderColor: theme.colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cancelButtonText: {
      fontSize: 15,
      fontWeight: '600',
      color: theme.colors.textSecondary,
    },
    confirmButton: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: theme.radius.md,
      backgroundColor: theme.colors.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    confirmButtonDisabled: {
      opacity: 0.6,
    },
    confirmButtonText: {
      fontSize: 15,
      fontWeight: '700',
      color: '#ffffff',
    },
  });
}
