import { StyleSheet } from 'react-native';
import { Theme } from '../../theme';

export function createResetOptionsModalStyles(theme: Theme) {
  return StyleSheet.create({
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.65)',
      justifyContent: 'flex-end',
    },
    container: {
      backgroundColor: theme.colors.surface,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: 20,
      paddingTop: 12,
      paddingBottom: 24,
      borderTopWidth: 1,
      borderLeftWidth: 1,
      borderRightWidth: 1,
      borderColor: theme.colors.border,
      maxHeight: '90%',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: -4 },
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 20,
    },
    dragHandle: {
      width: 42,
      height: 4.5,
      borderRadius: 2.5,
      backgroundColor: theme.colors.border,
      alignSelf: 'center',
      marginBottom: 16,
    },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 6,
    },
    headerTitleGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    headerIconCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: theme.colors.danger + '18',
      alignItems: 'center',
      justifyContent: 'center',
    },
    title: {
      color: theme.colors.textPrimary,
      fontSize: 18,
      fontWeight: '900',
    },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: theme.colors.background,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    subtitle: {
      color: theme.colors.textSecondary,
      fontSize: 13.5,
      lineHeight: 19,
      marginBottom: 16,
    },
    optionsList: {
      gap: 10,
      marginBottom: 16,
    },
    optionCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.background,
      borderRadius: 16,
      paddingVertical: 13,
      paddingHorizontal: 14,
      borderWidth: 1.5,
      borderColor: theme.colors.border,
      gap: 12,
    },
    optionCardSelected: {
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.accent + '12',
    },
    optionCardSelectedDanger: {
      borderColor: theme.colors.danger,
      backgroundColor: theme.colors.danger + '12',
    },
    optionIconsGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    optionIconCircle: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: theme.colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    radioCircle: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: theme.colors.textMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    radioCircleSelected: {
      borderColor: theme.colors.accent,
    },
    radioCircleSelectedDanger: {
      borderColor: theme.colors.danger,
    },
    radioDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: theme.colors.accent,
    },
    radioDotDanger: {
      backgroundColor: theme.colors.danger,
    },
    optionTextContent: {
      flex: 1,
    },
    optionTitle: {
      color: theme.colors.textPrimary,
      fontSize: 15,
      fontWeight: '800',
      marginBottom: 2,
    },
    optionDescription: {
      color: theme.colors.textSecondary,
      fontSize: 12.5,
      lineHeight: 18,
    },
    warningBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: theme.colors.danger + '10',
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 8,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: theme.colors.danger + '30',
    },
    warningText: {
      flex: 1,
      color: theme.colors.danger,
      fontSize: 12,
      lineHeight: 17,
      fontWeight: '600',
    },
    footer: {
      flexDirection: 'row',
      gap: 10,
    },
    cancelButton: {
      flex: 1,
      backgroundColor: theme.colors.background,
      paddingVertical: 13,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: theme.colors.border,
    },
    cancelButtonText: {
      color: theme.colors.textSecondary,
      fontSize: 15,
      fontWeight: '700',
    },
    confirmButton: {
      flex: 1.4,
      backgroundColor: theme.colors.danger,
      paddingVertical: 13,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    confirmButtonText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '800',
    },
  });
}
